### ISSUE TITLE
Uncaught InvalidAccessError on page load in Chrome: Failed to execute 'disconnect' on 'AudioNode'

### ISSUE THREAD

**Issue by JimmySticks2001** [processing/p5.js-sound#45]
Upon page load, this error will show in console:

> Uncaught InvalidAccessError: Failed to execute 'disconnect' on 'AudioNode': the given destination is not connected.

It halts program execution and I am unable to use the library. I am using Chrome 43.0.2357.65.

**Comment by therewasaguy** [comment]
Hi @JimmySticks2001 this is fixed in v0.1.9, which will be on the CDN soon but in the meantime you can grab the raw source code here on the github:

https://raw.githubusercontent.com/processing/p5.js-sound/master/lib/p5.sound.js

This issue is the same as https://github.com/processing/p5.js-sound/issues/41 and I'll leave this as an open ticket for others who encounter the same issue. I'm really sorry this happened, but the Web Audio API is constantly evolving and we will try to keep up!

**Comment by JimmySticks2001** [comment]
Thanks for letting me know. I tried to read through all the current and
past issues but I guess I misses that one.

**Comment by JimmySticks2001** [comment]
Sorry to be a nuisance, but there still appears to be an issue with the latest version. Now I am getting these errors:
![errors](http://i.imgur.com/Mt9UbQM.png)

It works fine in Firefox, not for Chrome or IE.

**Comment by therewasaguy** [comment]
This error message looks like a [CORS](http://en.wikipedia.org/wiki/Cross-origin_resource_sharing) issue. It happens when using loadSound() without a server—if you just open the index.html in a browser, the browser won't let you make the XMLHttpRequest needed to get the file. But if you run your sketch from a server, you can load files.

This page has info about running a local server:
https://github.com/processing/p5.js/wiki/Local-server

By the way, if all you want to do is play a sound file, you can use the p5.dom library and [createAudio()](http://p5js.org/reference/#/p5/createAudio) and that does not require a server. Alternately, if you want the user to choose which soundfiles to play by selecting files from their own filesystem, rather than hard coding the soundfile yourself, you can follow [this new example](https://github.com/processing/p5.js-sound/tree/master/examples/local_File_API).

**Comment by JimmySticks2001** [comment]
Excellent! Thanks for the info!

**Comment by Maay** [comment]
@therewasaguy 
guys, [i've got](http://bassfunk.moscow) the same problem just after i've updated my lib [to the suggested one here](https://github.com/processing/p5.js-sound/issues/45#issuecomment-105706491). Before updating the file I was having the "undifined function" error for the line `analyzer = new p5.Amplitude();` in my 'function draw'. Now, after first play (click on the [band icon](http://bassfunk.moscow)). Now I'm getting on my second play. It all happened spontaneously.

**Comment by Maay** [comment]
@therewasaguy iv'e updated lib from after merge and problem still appears.
`Uncaught InvalidAccessError: Failed to execute 'disconnect' on 'AudioNode': the given destination is not connected.
p5.Amplitude.setInput @ p5.sound.js:2011
(anonymous function) @ main.js?472bf453d925ca7a2c2f0af3587329be4138e659:46
(anonymous function) @ p5.sound.js:718`

in main.js:46 i've got this line `analyzer.setInput(mySound);` in:
`mySound = loadSound(need, function(){
 mySound.play();  
 analyzer.setInput(mySound);`

**Comment by therewasaguy** [comment]
thanks @Maay - it's possible that I had yet to merge the code. What version number? Try with 0.2.0

https://raw.githubusercontent.com/processing/p5.js-sound/master/lib/p5.sound.js

**Comment by Maay** [comment]
@therewasaguy it's fixed now, thanks a lot!

**Comment by therewasaguy** [comment]
glad to hear / sorry for the hassle and thanks for reporting it!
